### PR TITLE
Add CesiumDebugColorizeTilesRasterOverlay

### PR DESCRIPTION
**Pull request by kring**
A simple but handy debugging aid.

image

### CODE REVIEW

**Review by j9liu — COMMENTED** [review]
@kring looks good! I just had a question about the new overlay UI, and I pushed a commit for documentation.

**Comment by j9liu** [comment]
@kring just pushed the UI fix. Everything else looks good, so if you're okay with how the UI looks then I'm happy to merge
image

**Comment by kring** [comment]
Thanks @j9liu, your changes look good so I'm merging this.

**Comment by batesj** [comment]
I'm getting a Debug build failure that points to this CesiumDebugColorizeTilesRasterOverlay.h missing.

**Comment by j9liu** [comment]
Hi @batesj,

Just to clarify, this is when building Cesium for Unity via `cmake`, right? I'm not able to replicate this failure on my machine. What operating system are you using?

**Comment by batesj** [comment]
Building on Windows with cmake, yes. I'm synced to v0.3.1.

**Comment by batesj** [comment]
Ah, I see, it was a stale codegen issue. I edited CesiumFeatures.cs and then Unity generated sources correctly.

**Pull request merged**
