### PR TITLE
Add icon attributes to cesium scripts

### PR DESCRIPTION
**Pull request by csciguy8**
For all user facing Cesium scripts, instead of the using the default Unity script icon, use the Cesium logo.

A new 24x24 Cesium icon was created to match the rendering area of the icons in the Inspector and Add Component menu.

Resolves issue #191

### CODE REVIEW

**Comment by csciguy8** [comment]
@kring Kevin, do you have an opinion about scripts in the "Runtime" folder accessing resources in the "Editor" folder?

That's what this change is currently doing. It could be argued that the icon should be in the "Runtime/Resources" folder for organizational consistency, but in the end, it's an editor specific tag anyway, and none of this may really matter.

**Comment by kring** [comment]
Hmm yeah it's a good question. It does seem a little odd at first glance to have something in Runtime reference Editor. I tried to find examples of how others have structured their projects, and found that `com.unity.2d.animation` uses the same pattern you've used here. Others seem to utilize the fact that a simple string like `MyIcon` will (apparently) be resolved to `MyIcon.png` in any `Resources` directory anywhere. But using a full path seems safer.

All of which is a long way to say: this looks good to me. :)

**Comment by kring** [comment]
Just one request: please add a note to the Additions section of `CHANGES.md` mentioning that we've added icons.

**Comment by csciguy8** [comment]
Thanks for the insight Kevin. Also, I've added a note to `CHANGES.md` like you've requested.

**Comment by j9liu** [comment]
I'll go ahead and merge this. Thanks @csciguy8 !

**Pull request merged**
